In [2]:
#importing numpy library 

In [3]:
import numpy as np

In [4]:
l=["horse","dog","cat"]

In [5]:
l

['horse', 'dog', 'cat']

In [6]:
#sorting the given list using sort()

In [8]:
l.sort()
l

['cat', 'dog', 'horse']

In [9]:
#list function

In [10]:
li=list(range(6))

In [11]:
li

[0, 1, 2, 3, 4, 5]

In [12]:
#creating tuple

In [13]:
a=('Alex',32)

In [14]:
a

('Alex', 32)

In [15]:
b='Seema',26

In [16]:
b

('Seema', 26)

In [17]:
print(a[1])

32


In [18]:
print(b[0])

Seema


In [19]:
#1 dimensional array 

In [20]:
a=np.array([2,4,6,8])

In [21]:
a

array([2, 4, 6, 8])

In [22]:
a.dtype

dtype('int32')

In [23]:
a=np.array([2,4,6,8],np.int64)

In [24]:
a

array([2, 4, 6, 8], dtype=int64)

In [25]:
a

array([2, 4, 6, 8], dtype=int64)

In [28]:
a[1]

4

In [31]:
a.shape

(4,)

In [32]:
#creating 2D array 

In [33]:
listarr=np.array([[1,1,1],[2,2,2]])

In [34]:
listarr

array([[1, 1, 1],
       [2, 2, 2]])

In [37]:
a=np.array([[3,4,5,6,7],[2,6,8,9,1]])

In [38]:
a

array([[3, 4, 5, 6, 7],
       [2, 6, 8, 9, 1]])

In [39]:
a[1,3]

9

In [40]:
a[1][3]

9

In [41]:
#secific row

In [42]:
a[0]

array([3, 4, 5, 6, 7])

In [44]:
a[0, :]

array([3, 4, 5, 6, 7])

In [45]:
a[:,2]

array([5, 8])

In [46]:
#3d array

In [47]:
t=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [48]:
t

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [49]:
t[0,1,1]

4

In [50]:
#creating array of zeros

In [51]:
z=np.zeros((2,4))

In [52]:
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
#creating array of ones

In [57]:
z=np.ones((2,3,4))
z

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [58]:
#arange(): it gives range of array

In [60]:
x=np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])